# code deploy version
version: 0.0
# os
os: linux
# file to move
files:
  - source: /
    destination: /home/ec2-user/app/deploy/zip
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 7777

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 600
      runas: ec2-user
