spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate.default_batch_fetch_size: 1000
  batch:
    initialize-schema: always
    job:
      names: ${job.name:NONE}
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    initialization-mode: always
  flyway:
    enabled: false
