spring:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/evinfo?characterEncoding=UTF-8&serverTimezone=UTC
    username: kafka
    password: kafka
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false # 내가 만든 엔티티를 바탕으로 ddl을 만들어준다. 실제 서비스에서는 큰일남
  batch:
    job:
      names: ${job.name:NONE}
    initialize-schema: never
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  config:
    import: rest.yml
